//Eduardo de Oliveira Aguiar - RA: 2706954
public class FormFornecedor extends javax.swing.JFrame {
    private BDDados bd = BDDados.geraBD();
    private static FormFornecedor formForn;

    /**
     * Creates new form FormFornecedor
     */
    private FormFornecedor() {
        initComponents();
        this.setLocationRelativeTo(null);

        btIns.setBackground(new java.awt.Color(0, 153, 51));
        btIns.setForeground(java.awt.Color.WHITE);
        btIns.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btDel.setBackground(new java.awt.Color(204, 0, 0));
        btDel.setForeground(java.awt.Color.WHITE);
        btDel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btAlt.setBackground(new java.awt.Color(0, 102, 204));
        btAlt.setForeground(java.awt.Color.WHITE);
        btAlt.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btCons.setBackground(new java.awt.Color(102, 102, 102));
        btCons.setForeground(java.awt.Color.WHITE);
        btCons.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btLimpar.setBackground(java.awt.Color.WHITE);
        btSair.setBackground(new java.awt.Color(240, 240, 240));
    }
    // MÉTODO SINGLETON
    public static FormFornecedor geraFormForn() {
        if (formForn == null) formForn = new FormFornecedor();
        return formForn;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtEmpresa = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btIns = new javax.swing.JButton();
        btCons = new javax.swing.JButton();
        btAlt = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CNPJ:");

        jLabel2.setText("Nome Empresa:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Email:");

        txtEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaActionPerformed(evt);
            }
        });

        btIns.setText("Inserir Empresa");
        btIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsActionPerformed(evt);
            }
        });

        btCons.setText("Consultar Empresa (CNPJ)");
        btCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsActionPerformed(evt);
            }
        });

        btAlt.setText("Alterar Empresa (CNPJ)");
        btAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltActionPerformed(evt);
            }
        });

        btDel.setText("Excluir Empresa (CNPJ)");
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAlt)
                            .addComponent(btIns))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCons)
                            .addComponent(btDel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIns)
                    .addComponent(btCons))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlt)
                    .addComponent(btDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresaActionPerformed

    private void btInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsActionPerformed
        if(txtCnpj.getText().trim().isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(null, "CNPJ obrigatório!", "Erro", 0); return;
    }
    Fornecedor f = new Fornecedor();
    f.setCnpj(txtCnpj.getText().trim());
    f.setNomeEmpresa(txtEmpresa.getText().trim());
    f.setTelefone(txtTel.getText().trim());
    f.setEmail(txtEmail.getText().trim());
    
    if(bd.insForn(f) != null){
        javax.swing.JOptionPane.showMessageDialog(null, "Fornecedor cadastrado!", "Sucesso", 1);
        limpar();
    } else { javax.swing.JOptionPane.showMessageDialog(null, "CNPJ já existe!", "Erro", 0); }
        // TODO add your handling code here:
    }//GEN-LAST:event_btInsActionPerformed

    private void btConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsActionPerformed
        Fornecedor f = bd.consFornCnpj(txtCnpj.getText().trim());
    if(f != null){
        txtCnpj.setText(f.getCnpj());
        txtEmpresa.setText(f.getNomeEmpresa());
        txtTel.setText(f.getTelefone());
        txtEmail.setText(f.getEmail());
        javax.swing.JOptionPane.showMessageDialog(null, "Encontrado!", "Sucesso", 1);
    } else { javax.swing.JOptionPane.showMessageDialog(null, "Não encontrado", "Erro", 0); }
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsActionPerformed

    private void btAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltActionPerformed
        Fornecedor f = new Fornecedor();
    f.setCnpj(txtCnpj.getText().trim());
    if(bd.altForn(f) != null) {
        javax.swing.JOptionPane.showMessageDialog(null, "Atualizado!", "Sucesso", 1);
        btConsActionPerformed(evt);
    } else { javax.swing.JOptionPane.showMessageDialog(null, "Não encontrado", "Erro", 0); }
        // TODO add your handling code here:
    }//GEN-LAST:event_btAltActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        if(bd.delForn(txtCnpj.getText().trim()) != null){
        javax.swing.JOptionPane.showMessageDialog(null, "Removido!", "Sucesso", 1);
        limpar();
    } else { javax.swing.JOptionPane.showMessageDialog(null, "Não encontrado", "Erro", 0); }
        // TODO add your handling code here:
    }//GEN-LAST:event_btDelActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    /**
     * @param args the command line arguments
     */
   
     public void limpar(){
    txtCnpj.setText(""); txtEmpresa.setText(""); txtTel.setText("");
    txtEmail.setText(""); txtCnpj.requestFocus();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlt;
    private javax.swing.JButton btCons;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btIns;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
