//Eduardo de Oliveira Aguiar - RA: 2706954
public class FormRelatorio extends javax.swing.JFrame {
    private BDDados bd = BDDados.geraBD();
    private static FormRelatorio formRel;

    /**
     * Creates new form FormRelatorio
     */
    private FormRelatorio() {
        initComponents();
        
        btAtualizar.setBackground(new java.awt.Color(0, 102, 204)); 
        btAtualizar.setForeground(java.awt.Color.WHITE);
        btAtualizar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        
        tabClientes.setRowHeight(25);
        tabProdutos.setRowHeight(25);
        tabFunc.setRowHeight(25);
        tabForn.setRowHeight(25);
        tabVendas.setRowHeight(25);

        java.awt.Font fonteCabecalho = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12);
        
        tabClientes.getTableHeader().setFont(fonteCabecalho);
        tabProdutos.getTableHeader().setFont(fonteCabecalho);
        tabFunc.getTableHeader().setFont(fonteCabecalho);
        tabForn.getTableHeader().setFont(fonteCabecalho);
        tabVendas.getTableHeader().setFont(fonteCabecalho);

        this.setLocationRelativeTo(null);
    }
    //MÉTODO SINGLETON
    public static FormRelatorio geraRelatorio() {
        if (formRel == null) {
            formRel = new FormRelatorio();
        }
        return formRel;
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        carregarTabelas();
    }                                    

    private void carregarTabelas() {
        int qtdClientes = bd.getListaClientes().size();
        javax.swing.JOptionPane.showMessageDialog(null, "O Relatório está rodando!\nClientes encontrados no Banco: " + qtdClientes);
        javax.swing.table.DefaultTableModel modelCli = (javax.swing.table.DefaultTableModel) tabClientes.getModel();
        modelCli.setRowCount(0);
        for (Cliente c : bd.getListaClientes()) {
            modelCli.addRow(new Object[]{c.getNome(), c.getCpf(), c.getTelefone(), c.getEndereco()});
        }

        javax.swing.table.DefaultTableModel modelProd = (javax.swing.table.DefaultTableModel) tabProdutos.getModel();
        modelProd.setRowCount(0);
        for (Produto p : bd.getListaProdutos()) {
            modelProd.addRow(new Object[]{p.getNome(), p.getPreco(), p.getEstoque()});
        }

        javax.swing.table.DefaultTableModel modelFunc = (javax.swing.table.DefaultTableModel) tabFunc.getModel();
        modelFunc.setRowCount(0);
        for (Funcionario f : bd.getListaFuncionarios()) {
            modelFunc.addRow(new Object[]{f.getNome(), f.getCargo(), f.getSalario(), f.getTelefone(), f.getEmail()});
        }

        javax.swing.table.DefaultTableModel modelForn = (javax.swing.table.DefaultTableModel) tabForn.getModel();
        modelForn.setRowCount(0);
        for (Fornecedor f : bd.getListaFornecedores()) {
            modelForn.addRow(new Object[]{f.getNomeEmpresa(), f.getCnpj(), f.getTelefone(), f.getEmail()});
        }
        try {
            javax.swing.table.DefaultTableModel modelVendas = (javax.swing.table.DefaultTableModel) tabVendas.getModel();
            modelVendas.setRowCount(0);
            
            for (Venda v : bd.getListaVendas()) {
                modelVendas.addRow(new Object[]{
                    v.getCliente().getCpf(),       
                    v.getFuncionario().getNome(),  
                    v.getProduto().getNome(),      
                    v.getQuantidade()              
                });
            }
        } catch (Exception e) {
            System.out.println("Erro ao listar vendas: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAtualizar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabProdutos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabFunc = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabForn = new javax.swing.JTable();
        JPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabVendas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btAtualizar.setText("Atualizar Lista");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        tabClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CPF", "TELEFONE", "ENDEREÇO"
            }
        ));
        jScrollPane1.setViewportView(tabClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        tabProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "PREÇO", "ESTOQUE"
            }
        ));
        jScrollPane2.setViewportView(tabProdutos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Produtos", jPanel2);

        tabFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CARGO", "SALÁRIO", "TELEFONE", "EMAIL"
            }
        ));
        jScrollPane3.setViewportView(tabFunc);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Funcionários", jPanel3);

        tabForn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMPRESA", "CNPJ", "TELEFONE", "EMAIL"
            }
        ));
        jScrollPane4.setViewportView(tabForn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fornecedores", jPanel4);

        tabVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF DO CLIENTE", "FUNCIONÁRIO", "PRODUTO", "QUANTIDADE"
            }
        ));
        jScrollPane5.setViewportView(tabVendas);

        javax.swing.GroupLayout JPanel5Layout = new javax.swing.GroupLayout(JPanel5);
        JPanel5.setLayout(JPanel5Layout);
        JPanel5Layout.setHorizontalGroup(
            JPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        JPanel5Layout.setVerticalGroup(
            JPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vendas", JPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(btAtualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btAtualizar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        carregarTabelas();        // TODO add your handling code here:
    }//GEN-LAST:event_btAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel5;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabClientes;
    private javax.swing.JTable tabForn;
    private javax.swing.JTable tabFunc;
    private javax.swing.JTable tabProdutos;
    private javax.swing.JTable tabVendas;
    // End of variables declaration//GEN-END:variables
}
