//Eduardo de Oliveira Aguiar - RA: 2706954
public class FormCliente extends javax.swing.JFrame {
    private BDDados bd = BDDados.geraBD();
    private static FormCliente formCli;

    /**
     * Creates new form FormCliente
     */
    private FormCliente() {
        initComponents();
        this.setLocationRelativeTo(null);

        btIns.setBackground(new java.awt.Color(0, 153, 51));
        btIns.setForeground(java.awt.Color.WHITE);
        btIns.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btDel.setBackground(new java.awt.Color(204, 0, 0));
        btDel.setForeground(java.awt.Color.WHITE);
        btDel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btAlt.setBackground(new java.awt.Color(0, 102, 204));
        btAlt.setForeground(java.awt.Color.WHITE);
        btAlt.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btCons.setBackground(new java.awt.Color(102, 102, 102));
        btCons.setForeground(java.awt.Color.WHITE);
        btCons.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btLimpar.setBackground(java.awt.Color.WHITE);
        btSair.setBackground(new java.awt.Color(240, 240, 240));
    }
    //MÉTODO SINGLETON
    public static FormCliente geraFormCliente() {
        if (formCli == null) {
            formCli = new FormCliente();
        }
        return formCli;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNome = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEnd = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        btIns = new javax.swing.JButton();
        btCons = new javax.swing.JButton();
        btAlt = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNome.setText("Nome:");

        lbCpf.setText("CPF:");

        lbEndereco.setText("Endereço:");

        lbTelefone.setText("Telefone:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btIns.setText("Inserir Cliente");
        btIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsActionPerformed(evt);
            }
        });

        btCons.setText("Consultar Cliente (CPF)");
        btCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsActionPerformed(evt);
            }
        });

        btAlt.setText("Alterar Cliente (CPF)");
        btAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltActionPerformed(evt);
            }
        });

        btDel.setText("Excluir Cliente (CPF)");
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair)
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTelefone)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btIns)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbCpf)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(88, 88, 88)
                        .addComponent(lbEndereco))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btAlt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDel)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCons))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbEndereco)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpf)
                    .addComponent(lbTelefone)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIns)
                    .addComponent(btCons))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDel)
                    .addComponent(btAlt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsActionPerformed

    if (txtCpf.getText().trim().isEmpty() || txtNome.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Preencha pelo menos CPF e Nome!", "Alerta", 2);
        return; 
    }

    Cliente c = new Cliente();
    c.setCpf(txtCpf.getText().trim());
    c.setNome(txtNome.getText().trim());
    c.setEndereco(txtEnd.getText().trim());
    c.setTelefone(txtTel.getText().trim());

    if (bd.insCliente(c) != null) {
        javax.swing.JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!", "Sucesso", 1);
        limpar();
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Já existe um cliente com este CPF!", "Erro", 0);
    }

    }//GEN-LAST:event_btInsActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
          dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void btConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsActionPerformed

    String cpfProcurado = txtCpf.getText().trim();
    
    if (cpfProcurado.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Digite um CPF para consultar.", "Alerta", 2);
        return;
    }

    Cliente c = bd.consClienteCpf(cpfProcurado);

    if (c != null) {
        txtCpf.setText(c.getCpf());
        txtNome.setText(c.getNome());
        txtEnd.setText(c.getEndereco());
        txtTel.setText(c.getTelefone());
        
        javax.swing.JOptionPane.showMessageDialog(null, "Cliente encontrado: " + c.getNome(), "Sucesso", 1);
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Cliente não encontrado.", "Erro", 0);
    }
                                                              // TODO add your handling code here:
    }//GEN-LAST:event_btConsActionPerformed

    private void btAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltActionPerformed

    String cpfParaAlterar = txtCpf.getText().trim();
    
    if (cpfParaAlterar.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Digite o CPF do cliente que deseja alterar.", "Alerta", 2);
        return;
    }

    Cliente c = new Cliente();
    c.setCpf(cpfParaAlterar);

    Cliente atualizado = bd.altCliente(c);

    if (atualizado != null) {
        txtNome.setText(atualizado.getNome());
        txtEnd.setText(atualizado.getEndereco());
        txtTel.setText(atualizado.getTelefone());
        
        javax.swing.JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!", "Alteração", 1);
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "CPF não encontrado.", "Erro", 0);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btAltActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed

    String cpfParaExcluir = txtCpf.getText().trim();
    
    if (cpfParaExcluir.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Digite o CPF para excluir.", "Alerta", 2);
        return;
    }

    int confirma = javax.swing.JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Atenção", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirma == javax.swing.JOptionPane.YES_OPTION) {
        Cliente removido = bd.delCliente(cpfParaExcluir);

        if (removido != null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Cliente removido: " + removido.getNome(), "Exclusão", 1);
            limpar();
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "CPF não encontrado no sistema.", "Erro", 0);
        }
    }
                               // TODO add your handling code here:
    }//GEN-LAST:event_btDelActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void limpar() {
    txtCpf.setText("");
    txtNome.setText("");
    txtEnd.setText("");
    txtTel.setText("");
    txtCpf.requestFocus();
}
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlt;
    private javax.swing.JButton btCons;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btIns;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
