//Eduardo de Oliveira Aguiar - RA: 2706954
import javax.swing.JOptionPane;
public class FormVenda extends javax.swing.JFrame {
    private BDDados bd = BDDados.geraBD();
    private static FormVenda formVenda;

    /**
     * Creates new form FormVenda
     */
    private FormVenda() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        btInserir.setBackground(new java.awt.Color(0, 153, 51));
        btInserir.setForeground(java.awt.Color.WHITE);
        btInserir.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btExcluir.setBackground(new java.awt.Color(204, 0, 0));
        btExcluir.setForeground(java.awt.Color.WHITE);
        btExcluir.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btConsultar.setBackground(new java.awt.Color(0, 102, 204));
        btConsultar.setForeground(java.awt.Color.WHITE);
        btConsultar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btLimpar.setBackground(java.awt.Color.WHITE);
        btSair.setBackground(new java.awt.Color(240, 240, 240));
    }
    //MÉTODO SINGLETON
    public static FormVenda geraFormVenda() {
        if (formVenda == null) {
            formVenda = new FormVenda();
        }
        return formVenda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCpfCli = new javax.swing.JTextField();
        txtNomeFunc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        btInserir = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CPF do Cliente:");

        jLabel2.setText("Nome Funcionário:");

        jLabel3.setText("Nome Produto:");

        jLabel4.setText("Quantidade:");

        btInserir.setText("Inserir Venda");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar (CPF)");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir Venda");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btInserir)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btConsultar)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btExcluir)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultar)
                    .addComponent(btInserir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btExcluir)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed

    if(txtCpfCli.getText().isEmpty() || txtNomeProd.getText().isEmpty() || 
       txtNomeFunc.getText().isEmpty() || txtQtd.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Erro", 0);
        return;
    }

    Cliente c = bd.consClienteCpf(txtCpfCli.getText().trim());
    Funcionario f = bd.consFuncNome(txtNomeFunc.getText().trim());
    Produto p = bd.consProdutoNome(txtNomeProd.getText().trim());

    if(c == null){
        JOptionPane.showMessageDialog(null, "Cliente não encontrado (CPF).", "Erro", 0);
        return;
    }
    if(f == null){
        JOptionPane.showMessageDialog(null, "Funcionário não encontrado.", "Erro", 0);
        return;
    }
    if(p == null){
        JOptionPane.showMessageDialog(null, "Produto não encontrado.", "Erro", 0);
        return;
    }

    try {
        int qtd = Integer.parseInt(txtQtd.getText().trim());

        Venda v = new Venda();
        v.setCliente(c);
        v.setFuncionario(f);
        v.setProduto(p);
        v.setQuantidade(qtd);
        v.setDataVenda(java.time.LocalDate.now());

        bd.addVenda(v); 

        JOptionPane.showMessageDialog(null, "Venda registrada com sucesso!", "Sucesso", 1);
        limpar();

    } 
    catch (EstoqueException ex) { 
        JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro de Estoque", 0);
    } 
    catch (VendaException ex) { 
        JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro na Venda", 0);
    }
    catch (NumberFormatException e){ 
        JOptionPane.showMessageDialog(null, "Quantidade inválida! Digite apenas números.", "Erro", 0);
    }
          // TODO add your handling code here:
    }//GEN-LAST:event_btInserirActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        String cpf = txtCpfCli.getText().trim();
        if(cpf.isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o CPF do Cliente para excluir.", "Erro", 0);
            return;
        }
        
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza? O estoque será devolvido.", "Atenção", JOptionPane.YES_NO_OPTION);
        
        if(confirma == JOptionPane.YES_OPTION){
            if(bd.delVenda(cpf) != null){
                 JOptionPane.showMessageDialog(null, "Venda cancelada e estoque reposto!", "Sucesso", 1);
                 limpar();
            } else {
                 JOptionPane.showMessageDialog(null, "Venda não encontrada.", "Erro", 0);
            }
        }  // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
                                           
        String cpf = txtCpfCli.getText().trim();

        if(cpf.isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o CPF do Cliente para buscar.", "Erro", 0);
            return;
        }

        Venda v = bd.consVendaPorCliente(cpf);
        
        if(v != null){
            txtCpfCli.setText(v.getCliente().getCpf());
            txtNomeFunc.setText(v.getFuncionario().getNome());
            txtNomeProd.setText(v.getProduto().getNome());
            txtQtd.setText(String.valueOf(v.getQuantidade()));
            
            JOptionPane.showMessageDialog(null, "Venda encontrada!", "Sucesso", 1);
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma venda encontrada para este CPF.", "Aviso", 2);
            limpar();
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    /**
     * @param args the command line arguments
     */
    
         public void limpar(){
        txtCpfCli.setText("");
        txtNomeFunc.setText("");
        txtNomeProd.setText("");
        txtQtd.setText("");
        txtCpfCli.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCpfCli;
    private javax.swing.JTextField txtNomeFunc;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
