//Eduardo de Oliveira Aguiar - RA: 2706954
public class FormProduto extends javax.swing.JFrame {
    private BDDados bd = BDDados.geraBD();
    private static FormProduto formProd;

    /**
     * Creates new form FormProduto
     */
    private FormProduto() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        btIns.setBackground(new java.awt.Color(0, 153, 51));
        btIns.setForeground(java.awt.Color.WHITE);
        btIns.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btDel.setBackground(new java.awt.Color(204, 0, 0));
        btDel.setForeground(java.awt.Color.WHITE);
        btDel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btAlt.setBackground(new java.awt.Color(0, 102, 204));
        btAlt.setForeground(java.awt.Color.WHITE);
        btAlt.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btCons.setBackground(new java.awt.Color(102, 102, 102));
        btCons.setForeground(java.awt.Color.WHITE);
        btCons.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));

        btLimpar.setBackground(java.awt.Color.WHITE);
        btSair.setBackground(new java.awt.Color(240, 240, 240));
    }
    // MÉTODO SINGLETON
     public static FormProduto geraFormProduto() {
           if (formProd == null) formProd = new FormProduto();
           return formProd;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        btIns = new javax.swing.JButton();
        btCons = new javax.swing.JButton();
        btAlt = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Preço:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btIns.setText("Inserir Produto");
        btIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsActionPerformed(evt);
            }
        });

        btCons.setText("Consultar Produto (Nome)");
        btCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsActionPerformed(evt);
            }
        });

        btAlt.setText("Alterar Produto (Nome)");
        btAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltActionPerformed(evt);
            }
        });

        btDel.setText("Excluir Produto (Nome)");
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel4.setText("Estoque:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btIns)
                    .addComponent(btAlt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btDel)
                    .addComponent(btCons)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btSair)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIns)
                    .addComponent(btCons))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlt)
                    .addComponent(btDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsActionPerformed
        try {
            if(txtNome.getText().isEmpty() || txtPreco.getText().isEmpty() || txtEstoque.getText().isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Erro", 0);
                return;
            }

            String textoPreco = txtPreco.getText().replace(",", ".");
            double preco = Double.parseDouble(textoPreco);

            int estoque = Integer.parseInt(txtEstoque.getText());

           Produto p = new Produto(txtNome.getText(), preco, estoque);

            if(bd.insProduto(p) != null){
                javax.swing.JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!", "Sucesso", 1);
                limpar(); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Já existe um produto com este nome!", "Erro", 0);
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Preço ou Estoque inválidos! Verifique os números.", "Erro", 0);
        } // TODO add your handling code here:
    }//GEN-LAST:event_btInsActionPerformed

    private void btConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsActionPerformed
        Produto p = bd.consProdutoNome(txtNome.getText().trim());
    if(p != null){
        txtNome.setText(p.getNome());
        txtPreco.setText(String.valueOf(p.getPreco()));
        txtEstoque.setText(String.valueOf(p.getEstoque()));
        javax.swing.JOptionPane.showMessageDialog(null, "Encontrado!", "Sucesso", 1);
    } else { javax.swing.JOptionPane.showMessageDialog(null, "Não encontrado", "Erro", 0); }
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsActionPerformed

    private void btAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltActionPerformed

    String nomeBusca = txtNome.getText().trim();
    
    if(nomeBusca.isEmpty()){
         javax.swing.JOptionPane.showMessageDialog(null, "Digite o nome do produto para alterar.", "Erro", 0);
         return;
    }

    Produto pBusca = new Produto();
    pBusca.setNome(nomeBusca);

    Produto atualizado = bd.altProduto(pBusca);
    
    if(atualizado != null){
        txtPreco.setText(String.valueOf(atualizado.getPreco()).replace(".", ","));
        txtEstoque.setText(String.valueOf(atualizado.getEstoque()));
        javax.swing.JOptionPane.showMessageDialog(null, "Produto Atualizado!", "Sucesso", 1);
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Produto '" + nomeBusca + "' não encontrado.", "Erro", 0);
    }
         // TODO add your handling code here:
    }//GEN-LAST:event_btAltActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed

    String nomeExcluir = txtNome.getText().trim();

    if(nomeExcluir.isEmpty()){
         javax.swing.JOptionPane.showMessageDialog(null, "Digite o nome para excluir.", "Erro", 0);
         return;
    }
    int confirma = javax.swing.JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir '" + nomeExcluir + "'?", "Atenção", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if(confirma == javax.swing.JOptionPane.YES_OPTION) {
        if(bd.delProduto(nomeExcluir) != null){
            javax.swing.JOptionPane.showMessageDialog(null, "Produto removido com sucesso!", "Sucesso", 1);
            limpar();
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Produto não encontrado.", "Erro", 0);
        }
    }
             // TODO add your handling code here:
    }//GEN-LAST:event_btDelActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    /**
     * @param args the command line arguments
     */
     public void limpar(){
    txtNome.setText(""); txtPreco.setText(""); txtEstoque.setText(""); txtNome.requestFocus();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlt;
    private javax.swing.JButton btCons;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btIns;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
